name: bloc_06
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  intl: ^0.18.1
  fluttertoast: ^8.2.2
  connectivity_plus: ^4.0.2
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  path: ^1.8.3
  path_provider: ^2.0.15
  sqflite: ^2.3.0
  shared_preferences: ^2.2.0
  flutter_screenutil: ^5.8.4
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.1
  flutter_svg: ^2.0.7
  lottie: ^2.5.0
  dots_indicator: ^3.0.0
  meta: ^1.9.1
  equatable: ^2.0.5
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  firebase_core: ^2.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/voice/

  fonts:
    - family: Nunito
      fonts:
        - asset: font/Nunito-Bold.ttf
          weight: 700
        - asset: font/Nunito-Medium.ttf
          weight: 600
        - asset: font/Nunito-Regular.ttf
          weight: 400
