name: movies_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2

  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0

  dartz: ^0.10.1
  flare_flutter: ^3.0.2
  path_provider: ^2.1.1
  youtube_player_flutter: ^8.1.2
  intl: ^0.18.0
  get_it: ^7.6.4
  equatable: ^2.0.5
  dio: ^5.3.3
  connectivity_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/icons/
    - assets/languages/
    - assets/pngs/
    - assets/svgs/
